<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.develop.mvp</groupId>
        <artifactId>develop</artifactId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <modules>
        <module>develop-module-infra-api</module>
        <module>develop-module-infra-server</module>
    </modules>
    <artifactId>develop-module-infra</artifactId>
    <packaging>pom</packaging>

    <name>${project.artifactId}</name>
    <description>
        infra 模块，提供配置、文件、日志、数据源、WebSocket、定时任务等基础设施运维与管理能力。
    </description>

</project>
